BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "customers" ("id" integer primary key autoincrement not null, "account_number" varchar not null, "customer_name" varchar not null, "address_1" varchar not null, "address_2" varchar, "city" varchar not null, "state" varchar not null, "zip" varchar not null, "phone" varchar not null, "email" varchar not null, "business_type" varchar not null, "preferred_days" text, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "failed_jobs" ("id" integer primary key autoincrement not null, "uuid" varchar not null, "connection" text not null, "queue" text not null, "payload" text not null, "exception" text not null, "failed_at" datetime not null default CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "migrations" ("id" integer primary key autoincrement not null, "migration" varchar not null, "batch" integer not null);
CREATE TABLE IF NOT EXISTS "password_reset_tokens" ("email" varchar not null, "token" varchar not null, "created_at" datetime, primary key ("email"));
CREATE TABLE IF NOT EXISTS "personal_access_tokens" ("id" integer primary key autoincrement not null, "tokenable_type" varchar not null, "tokenable_id" integer not null, "name" varchar not null, "token" varchar not null, "abilities" text, "last_used_at" datetime, "expires_at" datetime, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "users" ("id" integer primary key autoincrement not null, "name" varchar not null, "email" varchar not null, "email_verified_at" datetime, "password" varchar not null, "remember_token" varchar, "created_at" datetime, "updated_at" datetime);
INSERT INTO "customers" ("id","account_number","customer_name","address_1","address_2","city","state","zip","phone","email","business_type","preferred_days","created_at","updated_at") VALUES (4,'ACCT-RNXUTQ','John Doe','123 Elm St','','Knoxville','TN','37918','865-555-1234','john@example.com','LLC','M,W,F','2025-04-30 16:37:54','2025-04-30 16:37:54');
INSERT INTO "customers" ("id","account_number","customer_name","address_1","address_2","city","state","zip","phone","email","business_type","preferred_days","created_at","updated_at") VALUES (5,'ACCT-8UBWWV','Jane Smith','456 Oak Ave','Suite 200','Oak Ridge','TN','37830','865-555-5678','jane@example.com','Corporation','T,R','2025-04-30 16:37:54','2025-04-30 16:37:54');
INSERT INTO "customers" ("id","account_number","customer_name","address_1","address_2","city","state","zip","phone","email","business_type","preferred_days","created_at","updated_at") VALUES (6,'ACCT-MYPKAD','Bob Builder','789 Construction Blvd','','Farragut','TN','37934','865-555-9999','bob@example.com','Sole Proprietor','M,T,W','2025-04-30 16:37:54','2025-04-30 16:37:54');
INSERT INTO "customers" ("id","account_number","customer_name","address_1","address_2","city","state","zip","phone","email","business_type","preferred_days","created_at","updated_at") VALUES (7,'ACCT-TWHSNO','Alice Johnson','321 Maple Dr','Apt B','Maryville','TN','37801','865-555-2222','alice@example.com','Other','F','2025-04-30 16:37:54','2025-04-30 16:37:54');
INSERT INTO "customers" ("id","account_number","customer_name","address_1","address_2","city","state","zip","phone","email","business_type","preferred_days","created_at","updated_at") VALUES (8,'ACCT-N2LBNB','Chuck Norris','987 Roundhouse Rd','','Sevierville','TN','37862','865-555-0000','chuck@example.com','LLC','M,R','2025-04-30 16:37:54','2025-04-30 16:37:54');
INSERT INTO "migrations" ("id","migration","batch") VALUES (1,'2014_10_12_000000_create_users_table',1);
INSERT INTO "migrations" ("id","migration","batch") VALUES (2,'2014_10_12_100000_create_password_reset_tokens_table',1);
INSERT INTO "migrations" ("id","migration","batch") VALUES (3,'2019_08_19_000000_create_failed_jobs_table',1);
INSERT INTO "migrations" ("id","migration","batch") VALUES (4,'2019_12_14_000001_create_personal_access_tokens_table',1);
INSERT INTO "migrations" ("id","migration","batch") VALUES (5,'2025_04_29_190213_create_customers_table',1);
CREATE UNIQUE INDEX "customers_account_number_unique" on "customers" ("account_number");
CREATE UNIQUE INDEX "customers_email_unique" on "customers" ("email");
CREATE UNIQUE INDEX "failed_jobs_uuid_unique" on "failed_jobs" ("uuid");
CREATE UNIQUE INDEX "personal_access_tokens_token_unique" on "personal_access_tokens" ("token");
CREATE INDEX "personal_access_tokens_tokenable_type_tokenable_id_index" on "personal_access_tokens" ("tokenable_type", "tokenable_id");
CREATE UNIQUE INDEX "users_email_unique" on "users" ("email");
COMMIT;
