version: '3.8'

services:
  laravel:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      DB_CONNECTION: sqlite
      DB_DATABASE: /app/database/database.sqlite
